VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IAppServices"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'public properties

Public Property Let MainTableName(ByVal vNewValue As String)
End Property

Public Property Let UsersTableName(ByVal vNewValue As String)
End Property

'public methods for Users Table

Public Sub GetAllUsersList()
End Sub

Public Sub AddNewUser()
End Sub

Public Sub UpdateUser()
End Sub

Public Sub DeleteUser()
End Sub



